version: '3'

services:
  traycable:
    image: thiagobarradas/wordpress:4.9.4-php7.2
    container_name: traycable.ir
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    ports:
      - 127.0.0.1:8120:80
    restart: unless-stopped
    networks:
      - traycable

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    env_file:
      - .env
    networks:
      - traycable

networks:
  traycable:

