version: '3'

services:
  traycable:
    image: thiagobarradas/wordpress:4.9.4-php7.2
    container_name: traycable_app
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    ports:
      - 127.0.0.1:8120:80
    restart: unless-stopped
    networks:
      - traycable

  mysql:
    image: mysql:8.0.32
    container_name: traycable_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./traycable_db_volume/:/var/lib/mysql
    restart: unless-stopped
    networks:
      - traycable

networks:
  traycable:
